name: Update icons

on:
  schedule:
  - cron: "5 0 * * 1" # “At 05:00 on Monday.”
  workflow_dispatch:

jobs:
  update:
    name: Update icons
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Update 'simple-icons'
      run: npm update simple-icons

    - name: Configure Git
      run: |
        git config --global user.name "Dhruv Bhanushali"
        git config --global user.email "dhruvkb@users.noreply.github.com"

    - name: Commit and push
      run: |
        git add package.json package-lock.json
        git commit -m "Update Simple Icons package"
        git push origin main
